import test from 'node:test';
import assert from 'node:assert/strict';
import {hasTransferConsents,saveAdminTransfer,loadAdminTransfers} from './transferAdminService.mjs';
const transfer={id:'request',organization_id:7,status:'pending',app_consent_required:true,player_id:'p',old_team_id:'o',new_team_id:'n'};
const consents=['player','old_team','new_team'].map(party=>({party,decision:'approved',subject_id:transfer[party==='player'?'player_id':`${party}_id`]}));
test('legacy web approvals require no mobile consent',()=>assert.equal(hasTransferConsents({status:'pending'}),true));
test('mobile approval requires three current participants',()=>{assert.equal(hasTransferConsents(transfer),false);assert.equal(hasTransferConsents({...transfer,transfer_consents:consents}),true);for(let i=0;i<3;i++){for(const replacement of [{...consents[i],decision:'rejected'},{...consents[i],subject_id:'foreign'}]){const list=[...consents];list[i]=replacement;assert.equal(hasTransferConsents({...transfer,transfer_consents:list}),false);}}assert.equal(hasTransferConsents({app_consent_required:true,transfer_consents:consents.map(c=>({...c,subject_id:undefined}))}),false);});
test('missing consent stops approval before any database write',async()=>{await assert.rejects(saveAdminTransfer({from(){assert.fail('Unexpected write')}},7,transfer,{status:'approved'}),/consent/)});
function client(result){const calls=[];const q={update(value){calls.push(['update',value]);return q},eq(...args){calls.push(['eq',...args]);return q},select(value){calls.push(['select',value]);return q},order(){return q},range(...args){calls.push(['range',...args]);return Promise.resolve(result)},single(){return Promise.resolve(result)}};return {calls,from(table){assert.equal(table,'transfers');return q}}}
test('approval is one status write scoped to request, organization and previous status',async()=>{const db=client({data:{id:'request'}});await saveAdminTransfer(db,7,{...transfer,transfer_consents:consents},{status:'approved'});assert.deepEqual(db.calls.filter(c=>c[0]==='eq'),[['eq','id','request'],['eq','organization_id',7],['eq','status','pending']]);assert.equal(db.calls.filter(c=>c[0]==='update').length,1)});
test('no updated row and stale/server failures never count as success',async()=>{for(const result of [{data:null},{error:new Error('stale')}])await assert.rejects(saveAdminTransfer(client(result),7,{...transfer,app_consent_required:false},{status:'approved'}))});
test('admin lists are bounded with one extra row for pagination',async()=>{const db=client({data:Array.from({length:31},(_,id)=>({id}))});const result=await loadAdminTransfers(db,7,'pending',2);assert.equal(result.items.length,30);assert.equal(result.hasMore,true);assert.deepEqual(db.calls.find(c=>c[0]==='range'),['range',60,90])});
